// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzQeldn0NJ6xneqgU8gnEvx547Ikgkco0',
    appId: '1:750147206453:web:54cce2e4d5da2019d2a07c',
    messagingSenderId: '750147206453',
    projectId: 'flutter-projects-push-ap-85caf',
    authDomain: 'flutter-projects-push-ap-85caf.firebaseapp.com',
    storageBucket: 'flutter-projects-push-ap-85caf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIfCHmtQy3ydLWTAmWwIeARXVTYtsdS4w',
    appId: '1:750147206453:android:a39547b908acfe75d2a07c',
    messagingSenderId: '750147206453',
    projectId: 'flutter-projects-push-ap-85caf',
    storageBucket: 'flutter-projects-push-ap-85caf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg_-l8tViWhIfz97LS7atunGKP3JLrOws',
    appId: '1:750147206453:ios:4a29300c4de0657cd2a07c',
    messagingSenderId: '750147206453',
    projectId: 'flutter-projects-push-ap-85caf',
    storageBucket: 'flutter-projects-push-ap-85caf.appspot.com',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg_-l8tViWhIfz97LS7atunGKP3JLrOws',
    appId: '1:750147206453:ios:4a29300c4de0657cd2a07c',
    messagingSenderId: '750147206453',
    projectId: 'flutter-projects-push-ap-85caf',
    storageBucket: 'flutter-projects-push-ap-85caf.appspot.com',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzQeldn0NJ6xneqgU8gnEvx547Ikgkco0',
    appId: '1:750147206453:web:5ed5d9b48146bc04d2a07c',
    messagingSenderId: '750147206453',
    projectId: 'flutter-projects-push-ap-85caf',
    authDomain: 'flutter-projects-push-ap-85caf.firebaseapp.com',
    storageBucket: 'flutter-projects-push-ap-85caf.appspot.com',
  );
}
